{- $v := include "app.values" . | fromYaml }
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { include "app5.fullname" . }
  labels: {- include "app5.labels" . | nindent 4 }
spec:
  replicas: { $v.replicaCount | default 1 }
  selector:
    matchLabels: {- include "app5.selectorLabels" . | nindent 6 }
  template:
    metadata:
      labels: {- include "app5.selectorLabels" . | nindent 8 }
    spec:
      containers:
        - name: { .Chart.Name }
          image: "{ $v.image.repository }:{ $v.image.tag }"
          imagePullPolicy: { $v.image.pullPolicy | default "IfNotPresent" }
          ports:
            - containerPort: { $v.containerPort | default 8080 }
          readinessProbe:
            httpGet: {- printf "{ path: "/", port: %s }" (default 8080 $v.containerPort) | nindent 12 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: {- printf "{ path: "/", port: %s }" (default 8080 $v.containerPort) | nindent 12 }
            initialDelaySeconds: 10
            periodSeconds: 10
