apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-matrix-test
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - env: dev
            clusterName: dev-cluster
            project: default
            nsPattern: dev-{{name}}          
      - list:
          elements:
          - name: app1
            chartPath: charts/app1
            image: docker.io/rajarammurali513/app1
            semver: ~1
          - name: app2
            chartPath: charts/app2
            image: docker.io/rajarammurali513/app2
            semver: ~1
          - name: app3
            chartPath: charts/app3
            image: docker.io/rajarammurali513/app3
            semver: ~1
          - name: app4
            chartPath: charts/app4
            image: docker.io/rajarammurali513/app4
            semver: ~1
          - name: app5
            chartPath: charts/app5
            image: docker.io/rajarammurali513/app5
            semver: ~1
  template:
    metadata:
      name: '{{name}}-{{env}}'
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{name}}={{image}}:{{semver}}'
        argocd-image-updater.argoproj.io/{{name}}.helm.image-name: apps.{{name}}.image.repository
        argocd-image-updater.argoproj.io/{{name}}.helm.image-tag: apps.{{name}}.image.tag
        argocd-image-updater.argoproj.io/{{name}}.update-strategy: semver
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/write-back-target: helmvalues:/envs/{{env}}/app.values.yaml
    spec:
      project: default
      source:
        repoURL: https://github.com/rajaramiotfal/sample-argocd-helm-5appsdd.git
        targetRevision: main
        path: '{{chartPath}}'
        helm:
          valueFiles:
          - '../envs/{{env}}/default.values.yaml'
          - '../envs/{{env}}/app.values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'dev-{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
