apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"ApplicationSet","metadata":{"annotations":{},"name":"apps-matrix-second","namespace":"argocd"},"spec":{"generators":[{"matrix":{"generators":[{"list":{"elements":[{"clusterName":"dev-cluster","env":"dev","nsPattern":"dev-{{name}}","project":"dev"},{"clusterName":"dev-cluster","env":"qa","nsPattern":"qa-{{name}}","project":"qa"},{"clusterName":"dev-cluster","env":"prod","nsPattern":"prod-{{name}}","project":"prod"}]}},{"list":{"elements":[{"chartPath":"charts/app1","image":"docker.io/rajarammurali513/app1","name":"app1","semver":"~1"},{"chartPath":"charts/app2","image":"docker.io/rajarammurali513/app2","name":"app2","semver":"~1"},{"chartPath":"charts/app3","image":"docker.io/rajarammurali513/app3","name":"app3","semver":"~1"},{"chartPath":"charts/app4","image":"docker.io/rajarammurali513/app4","name":"app4","semver":"~1"},{"chartPath":"charts/app5","image":"docker.io/rajarammurali513/app5","name":"app5","semver":"~1"}]}}]}}],"template":{"metadata":{"annotations":{"argocd-image-updater.argoproj.io/git-branch":"main","argocd-image-updater.argoproj.io/image-list":"{{name}}={{image}}:{{semver}}","argocd-image-updater.argoproj.io/write-back-method":"git","argocd-image-updater.argoproj.io/write-back-target":"helmvalues:/envs/{{env}}/app.values.yaml","argocd-image-updater.argoproj.io/{{name}}.helm.image-name":"apps.{{name}}.image.repository","argocd-image-updater.argoproj.io/{{name}}.helm.image-tag":"apps.{{name}}.image.tag","argocd-image-updater.argoproj.io/{{name}}.update-strategy":"semver"},"name":"{{name}}-{{env}}","namespace":"argocd"},"spec":{"destination":{"name":"{{clusterName}}","namespace":"{{nsPattern}}"},"project":"{{project}}","source":{"helm":{"valueFiles":["../envs/{{env}}/default.values.yaml","../envs/{{env}}/app.values.yaml"]},"path":"{{chartPath}}","repoURL":"https://github.com/rajaramiotfal/sample-argocd-helm-5appsdd.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}}}
    creationTimestamp: "2025-10-15T07:53:01Z"
    generation: 1
    name: apps-matrix-second
    namespace: argocd
    resourceVersion: "1782"
    uid: 0e0cd6a0-6764-44be-a9a3-ee71ca406b8a
  spec:
    generators:
    - matrix:
        generators:
        - list:
            elements:
            - clusterName: dev-cluster
              env: dev
              nsPattern: dev-{{name}}
              project: dev
            - clusterName: dev-cluster
              env: qa
              nsPattern: qa-{{name}}
              project: qa
            - clusterName: dev-cluster
              env: prod
              nsPattern: prod-{{name}}
              project: prod
        - list:
            elements:
            - chartPath: charts/app1
              image: docker.io/rajarammurali513/app1
              name: app1
              semver: ~1
            - chartPath: charts/app2
              image: docker.io/rajarammurali513/app2
              name: app2
              semver: ~1
            - chartPath: charts/app3
              image: docker.io/rajarammurali513/app3
              name: app3
              semver: ~1
            - chartPath: charts/app4
              image: docker.io/rajarammurali513/app4
              name: app4
              semver: ~1
            - chartPath: charts/app5
              image: docker.io/rajarammurali513/app5
              name: app5
              semver: ~1
    template:
      metadata:
        annotations:
          argocd-image-updater.argoproj.io/{{name}}.helm.image-name: apps.{{name}}.image.repository
          argocd-image-updater.argoproj.io/{{name}}.helm.image-tag: apps.{{name}}.image.tag
          argocd-image-updater.argoproj.io/{{name}}.update-strategy: semver
          argocd-image-updater.argoproj.io/git-branch: main
          argocd-image-updater.argoproj.io/image-list: '{{name}}={{image}}:{{semver}}'
          argocd-image-updater.argoproj.io/write-back-method: git
          argocd-image-updater.argoproj.io/write-back-target: helmvalues:/envs/{{env}}/app.values.yaml
        name: '{{name}}-{{env}}'
        namespace: argocd
      spec:
        destination:
          name: '{{clusterName}}'
          namespace: '{{nsPattern}}'
        project: '{{project}}'
        source:
          helm:
            valueFiles:
            - ../envs/{{env}}/default.values.yaml
            - ../envs/{{env}}/app.values.yaml
          path: '{{chartPath}}'
          repoURL: https://github.com/rajaramiotfal/sample-argocd-helm-5appsdd.git
          targetRevision: main
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
          - CreateNamespace=true
  status:
    conditions:
    - lastTransitionTime: "2025-10-15T07:53:02Z"
      message: Successfully generated parameters for all Applications
      reason: ApplicationSetUpToDate
      status: "False"
      type: ErrorOccurred
    - lastTransitionTime: "2025-10-15T07:53:02Z"
      message: Successfully generated parameters for all Applications
      reason: ParametersGenerated
      status: "True"
      type: ParametersGenerated
    - lastTransitionTime: "2025-10-15T07:53:02Z"
      message: ApplicationSet up to date
      reason: ApplicationSetUpToDate
      status: "True"
      type: ResourcesUpToDate
kind: List
metadata:
  resourceVersion: ""