replicaCount: 1
image:
  repository: docker.io/rajarammurali513/app1
  tag: "1.2.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
containerPort: 8080
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
  - host: app1.dev.local
    paths:
    - path: /
      pathType: Prefix
  tls: []
resources: {}
# Optional block used by env files to override per app:
apps: {app1: {image: {tag: 1.3.0, repository: docker.io/rajarammurali513/app1}}}
# values.yaml
nameOverride: ""
fullnameOverride: ""
env: dev
