{{- if or (eq .Values.env "dev") (eq .Values.env "qa") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: promote-{{ .Chart.Name }}-{{ .Values.env }}-to-next
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    # Tell Argo CD this is a PostSync hook
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: promote
          image: quay.io/argoproj/argocd:v2.9.3
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Promotion hook triggered for {{ .Chart.Name }} ({{ .Values.env }})"
              case "{{ .Values.env }}" in
                dev)
                  NEXT_ENV="qa"
                  ;;
                qa)
                  NEXT_ENV="prod"
                  ;;
                *)
                  echo "No promotion needed for {{ .Values.env }}"
                  exit 0
                  ;;
              esac

              NEXT_APP="{{ .Chart.Name }}-${NEXT_ENV}"
              echo "Syncing Argo CD application: ${NEXT_APP}"

              argocd app sync ${NEXT_APP} \
                --server argocd-server.argocd.svc.cluster.local \
                --username admin \
                --password "SwlWTFxpGRmUPBN1" \
                --grpc-web
                          
{{- end }}