{{- if or (eq .Values.env "dev") (eq .Values.env "qa") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: promote-{{ .Chart.Name }}-{{ .Values.env }}-to-next
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: promote
          image: argoproj/argocd:v2.10.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Promotion hook triggered for {{ .Chart.Name }} ({{ .Values.env }})"
              case "{{ .Values.env }}" in
                dev)
                  NEXT_ENV="qa"
                  ;;
                qa)
                  NEXT_ENV="prod"
                  ;;
                *)
                  echo "No promotion needed for {{ .Values.env }}"
                  exit 0
                  ;;
              esac

              NEXT_APP="{{ .Chart.Name }}-${NEXT_ENV}"
              echo "Syncing next application: ${NEXT_APP}"

              argocd app sync ${NEXT_APP} \
                --server argocd-server.argocd.svc.cluster.local \
                --username admin \
                --password "$ARGOCD_ADMIN_PWD" \
                --grpc-web

          env:
            - name: ARGOCD_ADMIN_PWD
              valueFrom:
                secretKeyRef:
                  name: argocd-initial-admin-secret
                  key: password
{{- end }}