apiVersion: batch/v1
kind: Job
metadata:
  name: promote-{{ .Chart.Name }}-{{ .Values.env }}-to-next
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: promote
          image: argoproj/argocd:v2.10.0
          command: ["/bin/sh", "-c"]
          args:
            - echo "Promotion triggered for {{ .Chart.Name }} in {{ .Values.env }}"
