replicaCount: 1

image:
  repository: docker.io/rajarammurali513/app2
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: app2.dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

# Optional block used by env files to override per app:
apps: {}
